### ISSUE TITLE
I put my password in and it just says N/A

### ISSUE THREAD

**Issue by TheRockettek** [Lignumm/CCJam-2016#2]
The title says it all :P :+1:

**Comment by Lemmmy** [comment]
The HTTPS certificate I use for Krist does not work in CCEmuRedux or Java 7. This is not a bug with Lignum's CCJam entry. To temporarily fix this problem, go to krist.lua and replace all `Krist.getNode(true)` with `Krist.getNode()`.

**Comment by Lignum** [comment]
I'll temporarily patch this when judging is done. Closed for now.
